---
extends:
  - airbnb/base
  - plugin:prettier/recommended
parser: babel-eslint
env:
  node: true
rules:
  quotes:
    - 2
    - single
    - avoid-escape
overrides:
  - files:
    - src/**/*.spec.js
    env:
      jest: true
